### ISSUE TITLE
dataset download problem

### ISSUE THREAD

**Issue by YajieW99** [taeinkwon/h2odataset#8]
Could you tell me about the problem I met when downloading the dataset? Thanks a lot !

Forbidden
You don't have permission to access this resource.
Apache/2.4.37 (Red Hat Enterprise Linux) Server at h2odataset.ethz.ch Port 443

**Comment by taeinkwon** [comment]
Hi @YajieW99 ,

Could you download it again? The problem is now fixed.

**Comment by YajieW99** [comment]
> 
Thanks for your reply, I can download it to my computer with Windows now. But it failed when I use 'wget' to download with Linux, then it worked when I change other datasets like 'mnist' using 'wget', so I'm not sure it's caused by the network or the 'wget' command.

**Comment by YajieW99** [comment]
@taeinkwon I have tried like that before, but it still cannot connect to the dataset website, maybe there's some problem with my server, thanks for your help.
